language: java
addons:
  sonarcloud:
    organization: "1908-aug19-java"
    token:
      secure: f4bd59b06d85b9f782e114602f1928f7dc65a523

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=1908-aug19-java_project2-joe-michael-backend
