language: java
addons:
  sonarcloud:
    organization: "1908-aug19-java"
    token:
      secure: travis encrypt bbe542a935380f1f83117d5cabb98e8fc7b05dfc

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=1908-aug19-java_project2-joe-michael-backend
